version: '3.8'

services:
  easy_ml:
      build: .
      container_name: easy_ml
      ports:
       - "8000:8000"
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
      depends_on:
        - redis

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"